const assert=require('node:assert/strict'),fs=require('node:fs'),crypto=require('node:crypto'),{chromium}=require('playwright');
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});try{
 const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[];page.setDefaultTimeout(120000);page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.text().startsWith('CAL:'))console.log(m.text())});await page.route('https://**',r=>r.abort());await page.addInitScript(()=>{const t=setTimeout;window.setTimeout=(f,d,...a)=>String(f).includes('loadSwiss().then')?0:t(f,d,...a)});
 const open=async()=>{await page.goto('file://'+process.cwd()+'/astrology_engine.html',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>document.querySelector('#validationTable').dataset.autorun==='done')};await open();
 console.log('CAL: startup');let state=await page.evaluate(()=>AstroHeatmap.getCalibration());assert.equal(state.events.length,27);assert.equal(state.resultCurrent,true);assert.equal(state.useFitted,true);assert.equal(state.fitRuns,0);assert.equal(state.result.validated,true);
 const embedded=await page.evaluate(()=>EMBEDDED_CALIBRATION_DATASET);assert.equal(crypto.createHash('sha256').update(JSON.stringify(embedded)).digest('hex'),'f2c8128f96f63f7cb33b995a87482af281d8dfac72f0e086621b10cc2e071ccc');
 await page.evaluate(async()=>{switchTab('calibration');const compute=computeCalibrationFit;computeCalibrationFit=()=>{throw Error('Unchanged calibration recomputed')};try{await fitCalibration();applyColdModel();await fitCalibration();}finally{computeCalibrationFit=compute}});
 assert.equal((await page.evaluate(()=>AstroHeatmap.getCalibration())).fitRuns,0);
 await page.evaluate(()=>applyColdModel());await open();assert.equal((await page.evaluate(()=>AstroHeatmap.getCalibration())).useFitted,false);await page.evaluate(()=>applyFittedModel());
 console.log('CAL: reload and reuse');const checks=await page.evaluate(async()=>{
  let n=0;const ok=(condition,message)=>{n++;if(!condition)throw Error(message)},base=structuredClone(CALIBRATION_STATE),reset=()=>{CALIBRATION_STATE=structuredClone(base);applyFittedModel(false)};
  for(const [key,value] of [['support',-1],['date','1990-01-01'],['endDate','2027-01-01'],['holdout',true],['confidence',1],['precision','year']]){reset();const e=CALIBRATION_STATE.events.find(e=>e[key]!==value);calUpdateEvent(e.id,key,value);ok(!calibrationResultCurrent()&&!CALIBRATION_STATE.useFitted,'Stale '+key);ok(JSON.stringify(VEDIC_LEVEL_WEIGHTS)===JSON.stringify(COLD_VEDIC_LEVEL_WEIGHTS),'Cold fallback '+key);ok(applyFittedModel(false)===false,'Stale fit rejected')}
  reset();CALIBRATION_STATE.optimizeRouting=false;render();ok(!CALIBRATION_STATE.useFitted&&!calibrationResultCurrent(),'Options invalidate');reset();CALIBRATION_STATE.autoApply=false;ok(calibrationResultCurrent(),'Auto apply does not change optimum');
  reset();const birth=profile.time;profile.time='22:56:00';ok(!calibrationResultCurrent(),'Birth invalidation');profile.time=birth;const provider=swissReady;swissReady=!provider;ok(!calibrationResultCurrent(),'Provider invalidation');swissReady=provider;
  reset();const originalProfile=profile;profile={...profile,name:'Other profile',date:'1987-05-09'};loadCalibrationState();ok(CALIBRATION_STATE.events.length===0&&!CALIBRATION_STATE.result,'No foreign-profile dataset or fit');profile=originalProfile;reset();const originalLayers=enabledStructuralLayerIds;enabledStructuralLayerIds=new Set(['D1']);ok(!calibrationResultCurrent(),'Structural settings invalidate');enabledStructuralLayerIds=originalLayers;
  reset();AstroHeatmap.setSystemRoutingMode('equal');ok(!CALIBRATION_STATE.useFitted,'Manual routing exits fitted model');reset();
  const date=Date.parse('2025-06-01T12:00:00Z'),di=0,period=findPeriodByPath(activePathAt(date,5));
  for(const weights of [COLD_VEDIC_LEVEL_WEIGHTS,base.result.dashaWeights])for(const metric of ['support','activation']){const predicted=calVedicMetricAt(date,di,metric,weights),old=VEDIC_LEVEL_WEIGHTS;VEDIC_LEVEL_WEIGHTS=[...weights];clearModelCaches();const actual=metric==='support'?scoreVedicPeriod(period,di):activationVedicPeriod(period,di);VEDIC_LEVEL_WEIGHTS=old;clearModelCaches();ok(Math.abs(predicted-actual)<1e-12,'Fit and applied Prana calculation agree')}
  console.log('CAL: Prana consistency');reset();const rows=structuredClone(CALIBRATION_STATE.events),fit=calFitRoutingMetric('support',rows,COLD_VEDIC_LEVEL_WEIGHTS,CANONICAL_WEIGHTS);rows.filter(e=>e.holdout).forEach(e=>e.support=-e.support);ok(JSON.stringify(fit)===JSON.stringify(calFitRoutingMetric('support',rows,COLD_VEDIC_LEVEL_WEIGHTS,CANONICAL_WEIGHTS)),'Holdouts excluded from training');
  console.log('CAL: holdout exclusion');reset();CALIBRATION_STATE.events[0].date='2025-02-30';let rejected=false;try{await fitCalibration()}catch(e){rejected=true}ok(rejected,'Invalid dates rejected');
  console.log('CAL: explicit fit');reset();CALIBRATION_STATE.events=CALIBRATION_STATE.events.slice(0,2).map(e=>({...e,holdout:false}));CALIBRATION_STATE.optimizeRouting=false;CALIBRATION_STATE.optimizeHierarchy=false;invalidateCalibration();await fitCalibration();ok(calibrationFitRuns===1,'One explicit computation for changed data');ok(CALIBRATION_STATE.result.validated===null&&!CALIBRATION_STATE.useFitted,'Provisional result not auto applied');await fitCalibration();ok(calibrationFitRuns===1,'Changed fit cached');
  reset();switchTab('calibration');return n;
 });
 assert(await page.locator('#calUseFittedBtn').isEnabled());assert(await page.locator('#calFitBtn').textContent()==='Use saved fit');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);await page.screenshot({path:'/tmp/kala-calibration-final.png'});
 await open();state=await page.evaluate(()=>AstroHeatmap.getCalibration());assert.equal(state.resultCurrent,true);assert.equal(state.fitRuns,0);
 const warning=await page.evaluate(()=>{const original=Storage.prototype.setItem;Storage.prototype.setItem=()=>{throw Error('disabled')};try{applyFittedModel(false);return {warning:calibrationStorageWarning,current:calibrationResultCurrent()}}finally{Storage.prototype.setItem=original}});assert(warning.warning.includes('session'));assert(warning.current);assert.deepEqual(errors,[]);console.log(JSON.stringify({checks,embeddedEvents:embedded.events.length,cacheReload:true,errors}));
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
