const assert=require('node:assert/strict'),{chromium}=require('playwright');
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});try{
 const page=await browser.newPage({viewport:{width:390,height:844},hasTouch:true}),errors=[];page.setDefaultTimeout(120000);page.on('pageerror',e=>errors.push(e.message));
 await page.route('https://**',r=>r.abort());await page.addInitScript(()=>{const t=setTimeout;window.setTimeout=(f,d,...a)=>String(f).includes('loadSwiss().then')?0:t(f,d,...a)});
 await page.goto('file://'+process.cwd()+'/astrology_engine.html');await page.waitForFunction(()=>document.querySelector('#validationTable').dataset.autorun==='done');
 const bands=await page.evaluate(()=>{
  const support=[-2,-1.2,-1.199,-.75,-.749,-.35,-.349,.11,.14,.349,.35,.749,.75,1.199,1.2,2].map(x=>directionSupportBand(x).label);
  const activation=[0,.349,.35,.749,.75,1.149,1.15,1.499,1.5,2].map(x=>directionActivationBand(x).label);
  const scale=[0,.35,.75,1.15,1.5].map(x=>directionScaleBand(x).label);
  const directions=[[.75,1.15,1.15],[.35,1.15,.5],[.35,.5,.5],[.1,1.15,1.15,95],[.1,1.15,.5],[.1,.5,.5],[-.35,1.15,.5],[-.35,.5,.5]].map(x=>directionFromScores(...x).action);
  return{support,activation,scale,directions,missing:directionFromScores(.5,null,.5).action,neutralColor:heatColor(.11)===heatColor(.14)&&heatColor(.14)===heatColor(0),mercury:scorePeriod(dashaRoot.find(p=>p.lord==='Mercury'&&p.a>chart.birthMs),0)};
 });
 assert.deepEqual(bands.support,['Very Difficult','Very Difficult','Difficult','Difficult','Challenging','Challenging','Mixed / Neutral','Mixed / Neutral','Mixed / Neutral','Mixed / Neutral','Good','Good','Great','Great','Exceptional','Exceptional']);
 assert.deepEqual(bands.activation,['Quiet','Quiet','Low','Low','Moderate','Moderate','High','High','Very High','Very High']);
 assert.deepEqual(bands.scale,['Local / Narrow','Limited Scale','Moderate Scale','Large Scale','Exceptional Scale']);
 assert.deepEqual(bands.directions,['EXPAND','ADVANCE','BUILD','PIVOT','SELECTIVE','HOLD','RESTRUCTURE','PROTECT']);assert.equal(bands.missing,'Not supplied');assert(bands.neutralColor);assert(Math.abs(bands.mercury-.2747501437659854)<1e-12);
 const audit=await page.evaluate(()=>{
  prefix=['Mercury','Venus','Mars'];switchTab('cycles');render();const period=findPeriodByPath(prefix),children=durationSummaryChildren(period);
  const before=DOMAINS.map((_,di)=>[scorePeriod(period,di),activationPeriod(period,di)]);
  const rows=DOMAINS.map((domain,di)=>{const value=scalePeriod(period,di),existing=domainExpressionAssessment(period,di)[1].score,mean=children.reduce((s,c)=>s+(c.b-c.a)*scalePeriod(c,di),0)/(period.b-period.a);return{domain,value,existing,mean}});
  return{rows,unchanged:JSON.stringify(before)===JSON.stringify(DOMAINS.map((_,di)=>[scorePeriod(period,di),activationPeriod(period,di)])),lifetimeDefault:$('contrastMode').value==='lifetime'};
 });
 console.log('Arithmetic checks complete');
 assert(audit.lifetimeDefault&&audit.unchanged);audit.rows.forEach(r=>{assert.equal(r.value,r.existing);assert(Math.abs(r.value-r.mean)<1e-12);assert(r.value>=0&&r.value<=2)});
 await page.locator('#scaleComparison > details > summary').click();await page.locator('#scaleHeat .touch-heat-cell').first().waitFor();
 assert.equal(await page.locator('#scaleHeat .touch-heat-cell').count(),108);console.log('Map rendered');
 const cell=page.locator('#scaleHeat .touch-heat-cell').first();assert((await cell.getAttribute('aria-label')).includes('Scale / reach'));await cell.scrollIntoViewIfNeeded();await page.waitForTimeout(250);await cell.tap();
 await page.locator('.heat-preview-evidence > summary').click();assert((await page.locator('.heat-magnifier').innerText()).includes('Authority / scale'));await page.keyboard.press('Escape');
 await page.locator('#scaleHeat button[data-view="details"]').click();assert((await page.locator('#scaleHeat').innerText()).includes('Expression 0–2'));
 await page.locator('#scaleHeat select').selectOption('Wealth');await page.locator('#scaleHeat .explorer-item').first().locator('summary').click();
 assert((await page.locator('#scaleHeat .explorer-item').first().innerText()).includes('Stewardship / continuity'));
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.locator('#scaleComparison').screenshot({path:'/tmp/kala-scale-mobile.png'});
 if(!await page.locator('#directionComparison > details').evaluate(e=>e.open))await page.locator('#directionComparison > details > summary').click();await page.locator('#directionHeat .direction-cell').first().waitFor();
 assert.equal(await page.locator('#directionHeat .direction-cell').count(),108);
 await page.locator('#directionHeat').scrollIntoViewIfNeeded();await page.screenshot({path:'/tmp/kala-direction-mobile.png'});
 const dc=page.locator('#directionHeat .direction-cell').first();await dc.scrollIntoViewIfNeeded();await page.waitForTimeout(250);await dc.tap();await page.locator('.heat-preview-evidence > summary').click();assert((await page.locator('.heat-magnifier').innerText()).includes('Direction'));assert.equal(await page.locator('.heat-magnifier .metric-number').count(),3);await page.keyboard.press('Escape');
 await page.locator('#directionHeat button[data-view="details"]').click();assert((await page.locator('#directionHeat').innerText()).includes('Primary action lens'));assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.evaluate(()=>{selectedSystemIds.delete('Vedic');renderScaleExplorer()});await page.waitForFunction(()=>document.querySelector('#scaleHeat').textContent.includes('Select Vedic'));
 assert.deepEqual(errors,[]);console.log('PASS: exact absolute bucket boundaries and retained action-category helpers, existing expression values, all-domain duration consistency, unchanged support/activation, lifetime default, mobile map/preview/details/key and absent-Vedic state.');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
