const assert=require('node:assert/strict'),crypto=require('node:crypto'),{chromium}=require('playwright');
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});try{const page=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('file://'+process.cwd()+'/mercury_atlas.html');
 const data=await page.evaluate(()=>SD_DATA);assert.equal(data.length,729);assert.equal(crypto.createHash('sha256').update(JSON.stringify(data)).digest('hex'),'640192b398514ac95005f5b80f8fd7a6e473918a2b6e902bbb9e75263137247f');
 const audit=await page.evaluate(()=>{let checked=0;for(const pd of DATA){const rows=sdByParent.get(pd.ad+'/'+pd.pd);if(rows.length!==9||rows[0].sd!==pd.pd||rows[0].start!==pd.start||rows.at(-1).end!==pd.end)throw Error('Parent grouping/boundaries');rows.forEach((r,i)=>{if(r.baseHeat!==pd.heat||r.pdPosture!==pd.posture||r.pdAssessment!==pd.assessment||Math.abs(r.heat-r.baseHeat)>1)throw Error('PD baseline mismatch');if(Date.parse(r.endExact)<=Date.parse(r.startExact)||Date.parse(r.midExact)<=Date.parse(r.startExact)||Date.parse(r.midExact)>=Date.parse(r.endExact))throw Error('Invalid times');if(i&&rows[i-1].endExact!==r.startExact)throw Error('Noncontiguous SDs');if(r.sd!==order[(order.indexOf(pd.pd)+i)%9])throw Error('Order');checked++})}return checked});assert.equal(audit,729);
 await page.locator('.cell.current').tap();assert(await page.locator('#pdPanel').isVisible());await page.locator('#sdTab').click();assert(await page.locator('#sdPanel').isVisible());assert.equal(await page.locator('.sd-segment').count(),9);assert(await page.evaluate(()=>{const r=sdByParent.get(sdParent.ad+'/'+sdParent.pd)[sdIndex];return Date.parse(r.startExact)<=Date.now()&&Date.now()<Date.parse(r.endExact)}));
 for(let i=0;i<9;i++){await page.selectOption('#sdSelect',String(i));assert.equal(await page.locator('.sd-segment[aria-pressed=true]').count(),1);assert(await page.evaluate(()=>{const r=sdByParent.get(sdParent.ad+'/'+sdParent.pd)[sdIndex],dates=[...document.querySelectorAll('#sdSelection time')].map(t=>t.dateTime);return dates[0]===r.startExact&&dates[1]===r.endExact&&$('sdSelection').textContent.includes(r.assessment)&&$('sdSelection').textContent.includes(r.sdLordTransit)}))}
 assert(await page.locator('#sdNext').isDisabled());await page.selectOption('#sdSelect','0');assert(await page.locator('#sdPrevious').isDisabled());await page.locator('#sdNext').click();assert.equal(await page.locator('#sdSelect').inputValue(),'1');await page.locator('.sd-segment').nth(3).tap();assert.equal(await page.locator('#sdSelect').inputValue(),'3');await page.locator('.sd-segment[aria-pressed=true]').press('ArrowRight');assert.equal(await page.locator('#sdSelect').inputValue(),'4');
 const geometry=await page.evaluate(()=>{const rows=sdByParent.get(sdParent.ad+'/'+sdParent.pd),total=Date.parse(rows.at(-1).endExact)-Date.parse(rows[0].startExact);return [...$('sdRibbon').children].every((b,i)=>Math.abs(b.getBoundingClientRect().width/$('sdRibbon').getBoundingClientRect().width-(Date.parse(rows[i].endExact)-Date.parse(rows[i].startExact))/total)<.002)});assert(geometry);
 const parent=await page.locator('#modalTitle').textContent();await page.locator('#next').click();assert.notEqual(await page.locator('#modalTitle').textContent(),parent);assert(await page.locator('#sdPanel').isVisible());assert.equal(await page.locator('.sd-segment').count(),9);
 await page.locator('#sdTab').focus();await page.keyboard.press('ArrowLeft');assert(await page.locator('#pdPanel').isVisible());await page.keyboard.press('ArrowRight');assert(await page.locator('#sdPanel').isVisible());
 for(const width of [320,390,430,1024]){await page.setViewportSize({width,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth&&modal.scrollWidth<=modal.clientWidth+1));}
 await page.setViewportSize({width:390,height:844});await page.locator('#sdSelect').scrollIntoViewIfNeeded();await page.screenshot({path:'/tmp/mercury-sookshma-mobile.png'});await page.locator('#closeModal').click();assert.equal(await page.locator('.cell:visible').count(),81);assert.equal(await page.locator('#selection').count(),0);await page.locator('.cell').first().tap();assert(await page.locator('#pdPanel').isVisible());assert.deepEqual(errors,[]);console.log('PASS: 729 SD records exact; all 81 parent groups and date boundaries; current SD; composite limits; duration ribbon; dropdown/arrows/touch; popup tabs and parent navigation; 320–1024px fit.');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
