const assert=require('node:assert/strict'),fs=require('node:fs'),crypto=require('node:crypto'),{chromium}=require('playwright');
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});try{const page=await browser.newPage({viewport:{width:390,height:844},hasTouch:true,isMobile:true}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('file://'+process.cwd()+'/mercury_dasha_atlas.html');
 assert.equal(await page.locator('.cell').count(),81);assert.equal(await page.locator('table').count(),0);
 const data=await page.evaluate(()=>({DATA,PRACTICE}));assert.equal(crypto.createHash('sha256').update(JSON.stringify(data)).digest('hex'),'f4414de7f003d69bd66e23ed379fe08375575c1256e2bc7f0893f3a35cf95f46');
 for(const width of [320,390,430,1024]){await page.setViewportSize({width,height:844});await page.waitForTimeout(70);const fit=await page.evaluate(()=>({page:document.documentElement.scrollWidth<=innerWidth,grid:viewport.scrollWidth<=viewport.clientWidth+1,height:viewport.scrollHeight<=viewport.clientHeight+1}));assert.deepEqual(fit,{page:true,grid:true,height:true})}
 await page.setViewportSize({width:390,height:844});await page.locator('#zoomIn').click();await page.locator('#zoomIn').click();assert.equal(await page.locator('#zoomValue').textContent(),'200%');
 const map=await page.locator('#minimap').boundingBox();await page.mouse.click(map.x+map.width-5,map.y+map.height-5);assert(await page.evaluate(()=>viewport.scrollLeft>0&&viewport.scrollTop>0));await page.locator('#fit').click();assert.equal(await page.evaluate(()=>viewport.scrollLeft+viewport.scrollTop),0);
 await page.locator('.cell').nth(13).click();assert.equal(await page.locator('.cell[aria-selected=true]').count(),1);await page.locator('.cell[aria-selected=true]').press('ArrowRight');assert.equal(await page.locator('.cell[aria-selected=true]').getAttribute('data-col'),'5');
 await page.locator('#details').click();assert(await page.locator('#detailModal').isVisible());assert.equal(await page.locator('.planet').count(),9);await page.locator('#closeModal').click();
 await page.locator('#filters summary').click();await page.locator('#search').fill('no-match-xyz');assert.equal(await page.locator('.cell.dim').count(),81);assert.equal(await page.locator('#stats').textContent(),'0 / 81');await page.locator('#reset').click();await page.selectOption('#adFilter','Venus');assert.equal(await page.locator('.cell:not(.dim)').count(),9);await page.locator('#reset').click();await page.locator('#filters summary').click();
 await page.locator('#inspect').click();const cell=await page.locator('.cell').nth(40).boundingBox();await page.mouse.move(cell.x+cell.width/2,cell.y+cell.height/2);await page.mouse.down();assert(await page.locator('#lens').isVisible());assert.equal(await page.locator('.lens-grid div').count(),9);await page.mouse.move(cell.x+cell.width*1.5,cell.y+cell.height/2);const label=await page.locator('#lens strong').first().textContent();assert(label.includes('Mars'));await page.mouse.up();assert(!await page.locator('#lens').isVisible());await page.locator('#inspect').click();
 const cdp=await page.context().newCDPSession(page),box=await page.locator('#viewport').boundingBox(),x=box.x+box.width/2,y=box.y+box.height/2;
 await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:x-25,y,id:1},{x:x+25,y,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x-65,y,id:1},{x:x+65,y,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert(await page.evaluate(()=>zoom>2));await page.locator('#fit').click();
 await page.locator('#today').click();await page.screenshot({path:'/tmp/mercury-atlas-mobile.png',fullPage:true});assert.deepEqual(errors,[]);console.log('PASS: 81 records preserved; phone/desktop fit; zoom, minimap, selection, keyboard, filters, details, moving lens and touch pinch.');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
