const assert=require('node:assert/strict'),crypto=require('node:crypto'),{chromium}=require('playwright');
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});try{
 const page=await browser.newPage({viewport:{width:390,height:844},hasTouch:true,isMobile:true}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('file://'+process.cwd()+'/mercury_atlas.html');
 assert.equal(await page.locator('.cell').count(),81);assert.equal(await page.locator('.cell:visible').count(),81);assert.equal(await page.locator('#selection').count(),0);assert.equal(await page.locator('table').count(),0);
 const careerHeats=await page.evaluate(()=>DATA.map(r=>pdResult(r,'career').heat));
 const data=await page.evaluate(()=>({DATA,PRACTICE}));assert.equal(crypto.createHash('sha256').update(JSON.stringify(data)).digest('hex'),'f4414de7f003d69bd66e23ed379fe08375575c1256e2bc7f0893f3a35cf95f46');
 assert.equal(await page.locator('#adSlider').count(),0);
 assert(await page.evaluate(()=>groups.every(entries=>entries.every(({r,i},j)=>{const b=cells.find(c=>+c.dataset.index===i),width=b.getBoundingClientRect().width,total=b.parentElement.getBoundingClientRect().width,ratio=(Date.parse(r.end)-Date.parse(r.start))/(Date.parse(entries.at(-1).r.end)-Date.parse(entries[0].r.start));return Math.abs(width/total-ratio)<.002&&(!j||entries[j-1].r.end===r.start)}))));
 for(const width of [320,390,430,1024]){await page.setViewportSize({width,height:844});await page.waitForTimeout(60);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth&&viewport.scrollWidth<=viewport.clientWidth+1&&viewport.scrollHeight<=viewport.clientHeight+1));assert.equal(await page.locator('.timeline-row:visible').count(),9)}
 await page.setViewportSize({width:390,height:844});await page.locator('.cell').nth(21).tap();assert(await page.locator('#detailModal').isVisible());assert.equal(await page.locator('#pdPanel .planet').count(),9);assert((await page.locator('#modalTitle').textContent()).includes('Venus AD'));await page.locator('#next').click();assert((await page.locator('#modalTitle').textContent()).includes('Rahu PD'));await page.locator('#closeModal').click();assert(!await page.locator('#detailModal').isVisible());
 await page.locator('.cell').nth(8).click();await page.locator('#next').click();assert.equal(await page.locator('#modalTitle').textContent(),'Ketu AD → Ketu PD');await page.keyboard.press('Escape');assert(!await page.locator('#detailModal').isVisible());await page.locator('.cell[aria-selected=true]').press('ArrowRight');await page.locator('.cell[aria-selected=true]').press('Enter');assert((await page.locator('#modalTitle').textContent()).includes('Venus PD'));await page.locator('#closeModal').click();
 await page.locator('#zoomIn').click();await page.locator('#zoomIn').click();assert.equal(await page.locator('#zoomValue').textContent(),'200%');await page.locator('#minimap').evaluate(e=>e.scrollIntoView({block:'center'}));const map=await page.locator('#minimap').boundingBox();await page.mouse.click(map.x+map.width-5,map.y+map.height-5);assert(await page.evaluate(()=>viewport.scrollLeft>0));await page.locator('#viewport').evaluate(e=>e.scrollIntoView({block:'center'}));const pan=await page.locator('#viewport').boundingBox();await page.mouse.move(pan.x+pan.width*.5,pan.y+pan.height*.65);await page.mouse.down();await page.mouse.move(pan.x+pan.width*.8,pan.y+pan.height*.65,{steps:5});await page.mouse.up();assert(!await page.locator('#detailModal').isVisible());await page.locator('#fit').click();
 await page.locator('#filters summary').click();await page.locator('#search').fill('no-match-xyz');assert.equal(await page.locator('.cell.dim').count(),81);assert.equal(await page.locator('#stats').textContent(),'0 / 81 PDs');await page.locator('#reset').click();await page.selectOption('#adFilter','Venus');assert.equal(await page.locator('.timeline-row:visible').count(),9);assert.equal(await page.locator('.cell:not(.dim)').count(),9);await page.locator('#reset').click();await page.locator('#filters summary').click();
 for(let heat=1;heat<=5;heat++){await page.locator(`#legend [data-heat="${heat}"]`).tap();assert.equal(await page.locator('#heatFilter').inputValue(),String(heat));assert.equal(await page.locator('#legend [aria-pressed=true]').count(),1);assert.equal(await page.locator('.cell:not(.dim)').count(),careerHeats.filter(h=>h===heat).length);await page.locator(`#legend [data-heat="${heat}"]`).tap();assert.equal(await page.locator('.cell:not(.dim)').count(),81)}
 await page.locator('#filters summary').click();await page.selectOption('#adFilter','Venus');await page.selectOption('#heatFilter','2');assert.equal(await page.locator('#legend [data-heat="2"]').getAttribute('aria-pressed'),'true');assert.equal(await page.locator('.cell:not(.dim)').count(),data.DATA.filter((r,i)=>r.ad==='Venus'&&careerHeats[i]===2).length);await page.locator('#legend [data-heat=""]').click();assert.equal(await page.locator('.cell:not(.dim)').count(),9);await page.locator('#legend [data-heat="4"]').focus();await page.keyboard.press('Enter');assert.equal(await page.locator('#heatFilter').inputValue(),'4');await page.locator('#reset').click();assert.equal(await page.locator('#legend [data-heat=""]').getAttribute('aria-pressed'),'true');await page.locator('#filters summary').click();
 await page.locator('#inspect').click();assert((await page.locator('#gestureHint').textContent()).includes('Inspect is on'));await page.locator('#viewport').evaluate(e=>e.scrollIntoView({block:'center'}));const cell=await page.locator('.cell:visible').nth(4).boundingBox();await page.mouse.move(cell.x+cell.width/2,cell.y+cell.height/2);await page.mouse.down();assert(await page.locator('#lens').isVisible());assert.equal(await page.locator('.lens-grid div').count(),3);const adjacent=await page.locator('.cell:visible').nth(5).boundingBox();await page.mouse.move(adjacent.x+adjacent.width/2,adjacent.y+adjacent.height/2);await page.mouse.up();assert(!await page.locator('#lens').isVisible());assert(!await page.locator('#detailModal').isVisible());await page.locator('#inspect').click();
 await page.locator('#viewport').evaluate(e=>e.scrollIntoView({block:'center'}));const cdp=await page.context().newCDPSession(page),box=await page.locator('#viewport').boundingBox(),x=box.x+box.width/2,y=box.y+box.height/2;await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:x-25,y,id:1},{x:x+25,y,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x-65,y,id:1},{x:x+65,y,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert(await page.evaluate(()=>zoom>2));assert(!await page.locator('#detailModal').isVisible());await page.locator('#fit').click();await page.locator('#today').click();await page.screenshot({path:'/tmp/mercury-atlas-mobile.png',fullPage:true});await page.locator('.cell.current').tap();await page.screenshot({path:'/tmp/mercury-atlas-popup.png'});assert.deepEqual(errors,[]);
 console.log('PASS: preserved 81 records; all nine ADs in one plot; duration geometry; phone/desktop fit; tap/keyboard popup and cross-AD navigation; filters; minimap; magnifier; pinch without accidental popup.');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
